### PR TITLE
Re-enable tests

### LINKED ISSUE #2: Broken Test: io.vlingo.symbio.store.state.dynamodb.DynamoDBTextStateActorTest
@kmruiz 

ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
vlingo/actors: vlingo/actors: Generating proxy for main: io.vlingo.common.Scheduled
Mar 25, 2019 5:03:31 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] SQLiteDBAccess$20@7a05f3d: job exception
com.amazonaws.services.dynamodbv2.local.shared.exceptions.LocalDBAccessException: A non-existing table was accessed.
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccessJob.getTableSchemaInfo2(SQLiteDBAccessJob.java:61)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:1792)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:1787)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:97)
	at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
	at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.lang.Thread.run(Thread.java:748)

ERROR LocalDynamoDBServerHandler Unexpected exception occured
 com.amazonaws.services.dynamodbv2.local.shared.exceptions.LocalDBAccessException: A non-existing table was accessed.
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccessJob.getTableSchemaInfo2(SQLiteDBAccessJob.java:61)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:1792)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$20.doWork(SQLiteDBAccess.java:1787)
	at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:97)
	at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
	at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by jakzal**
Fixes #2

### CODE REVIEW

File: src/test/java/io/vlingo/xoom/symbio/store/state/dynamodb/DynamoDBBinaryStateActorTest.java [hunk 1]
```diff
@@ -60,36 +56,30 @@ public void setUp() {
...
 
     @Override
-//    protected void verifyDispatched(List<Dispatcher<Dispatchable<Entry<?>, BinaryState>>> dispatchers, String id, BinaryState state) {
-//        verify(dispatchers, timeout(DEFAULT_TIMEOUT)).dispatch(new Dispatchable<>(id, LocalDateTime.now(), state, Collections.emptyList()));
-//    }
-    protected void verifyDispatched(Dispatcher<Dispatchable<Entry<?>, BinaryState>> dispatcher, String id, BinaryState state) {
-      verify(dispatcher, timeout(DEFAULT_TIMEOUT)).dispatch(new Dispatchable<>(id, LocalDateTime.now(), state, Collections.emptyList()));
-  }
+    protected void verifyDispatched(List<Dispatcher<Dispatchable<Entry<?>, BinaryState>>> dispatchers, String id, BinaryState state) {
+      dispatchers.forEach(dispatcher -> verify(dispatcher, timeout(DEFAULT_TIMEOUT).atLeast(1)).dispatch(new Dispatchable<>(id, LocalDateTime.now(), state, Collections.emptyList())));
```
Comment (jakzal) [inline src/test/java/io/vlingo/xoom/symbio/store/state/dynamodb/DynamoDBBinaryStateActorTest.java:81]: @VaughnVernon I am not sure if this is intended, but dispatchers are called more than once by most of tests (twice, with some extreme cases of 7 times).
